    OPTION(FETCHCONTENT_QUIET OFF)
    cmake_policy(SET CMP0077 NEW)
    set (OpenCV_DIR "${opencv_SOURCE_DIR}/cmake/opencv4")
    OPTION(WITH_ARITH_ENC OFF)
    OPTION(BUILD_PERF_TESTS OFF)
    OPTION(BUILD_opencv_java_bindings_generator OFF)
    OPTION(lzw OFF)
    OPTION(WITH_FFMPEG OFF)
    OPTION(BUILD_opencv_photo OFF)
    OPTION(BUILD_PACKAGE OFF)
    OPTION(BUILD_opencv_imgcodecs OFF)
    OPTION(BUILD_opencv_gapi OFF)
    OPTION(WITH_OPENJPEG OFF)
    OPTION(WITH_QT OFF)
    OPTION(ccitt OFF)
    OPTION(BUILD_opencv_apps OFF)
    OPTION(WITH_OPENCLAMDBLAS OFF)
    SET(CMAKE_BUILD_TYPE "Release")
    OPTION(BUILD_PROTOBUF OFF)
    OPTION(WITH_QUIRC OFF)
    OPTION(CV_TRACE OFF)
    OPTION(WITH_IMGCODEC_PFM OFF)
    OPTION(BUILD_opencv_stitching OFF)
    OPTION(thunder OFF)
    OPTION(BUILD_opencv_videoio OFF)
    OPTION(WITH_OPENCL OFF)
    OPTION(WITH_TIFF OFF)
    OPTION(BUILD_opencv_python_bindings_generator OFF)
    OPTION(WITH_GTK OFF)
    OPTION(WITH_ADE OFF)
    OPTION(WITH_V4L OFF)
    OPTION(WITH_LAPACK OFF)
    OPTION(WITH_PTHREADS_PF OFF)
    OPTION(WITH_OPENCLAMDFFT OFF)
    OPTION(logluv OFF)
    OPTION(BUILD_opencv_calib3d OFF)
    OPTION(WITH_WEBP OFF)
    OPTION(packbits OFF)
    OPTION(WITH_IMGCODEC_PXM OFF)
    OPTION(BUILD_opencv_ts OFF)
    OPTION(WITH_IMGCODEC_HDR OFF)
    OPTION(BUILD_opencv_python_tests OFF)
    OPTION(WITH_TBB OFF)
    OPTION(BUILD_IPP_IW OFF)
    OPTION(BUILD_opencv_video OFF)
    OPTION(WITH_JASPER OFF)
    OPTION(WITH_ARITH_DEC OFF)
    OPTION(WITH_PROTOBUF OFF)
    OPTION(WITH_GSTREAMER OFF)
    OPTION(BUILD_WEBP OFF)
    OPTION(WITH_IPP OFF)
    OPTION(WITH_PNG OFF)
    OPTION(WITH_ITT OFF)
    OPTION(BUILD_opencv_objdetect OFF)
    OPTION(CV_ENABLE_INTRINSICS OFF)
    OPTION(BUILD_SHARED_LIBS OFF)
    OPTION(BUILD_opencv_highgui OFF)
    OPTION(BUILD_opencv_dnn OFF)
    OPTION(BUILD_opencv_flann OFF)
    OPTION(WITH_GPHOTO2 OFF)
    OPTION(WITH_JPEG OFF)
    OPTION(mdi OFF)
    OPTION(WITH_IMGCODEC_SUNRASTER OFF)
    OPTION(BUILD_opencv_ml OFF)
    OPTION(BUILD_opencv_js OFF)
    OPTION(BUILD_ITT OFF)
    OPTION(WITH_1394 OFF)
    OPTION(BUILD_TESTS OFF)
    OPTION(next OFF)
    SET(CPU_BASELINE STRING "")
    SET(CPU_DISPATCH STRING "")
    SET(OpenCV_STATIC ON)
    if (CMAKE_SYSTEM_NAME STREQUAL "Emscripten")
        # https://stackoverflow.com/questions/55869531/how-to-use-emscripten-with-cmake-for-project-dependencies
        SET (CMAKE_CXX_FLAGS  "-O3 --llvm-lto 1 --bind -s ASSERTIONS=2 -s NO_FILESYSTEM=1 -s NO_EXIT_RUNTIME=1 --memory-init-file 0")
        set (CMAKE_C_FLAGS "-O3 --llvm-lto 1 --bind -s ASSERTIONS=2 -s NO_FILESYSTEM=1 -s NO_EXIT_RUNTIME=1 --memory-init-file 0")
    endif()

        # find_package(OpenCV ${OPENCV_VERSION} REQUIRED PATHS "${opencv_SOURCE_DIR}/../.." REQUIRED COMPONENTS core imgproc)
    # Needed for opencv2/opencv.hpp
    include_directories( ${OpenCV_SOURCE_DIR}/include )

    message("Source dir ${CMAKE_CURRENT_SOURCE_DIR}  Build dir ${CMAKE_CURRENT_BINARY_DIR}")
    # Needed by opencv.hpp for opencv2/opencv_modules.hpp
    include_directories( "${CMAKE_CURRENT_BINARY_DIR}/../" )

    # Needed by opencv_modules.hpp for every module
    message("${OpenCV_SOURCE_DIR}/modules/*/include" )
    file( GLOB opencv_include_modules "${OpenCV_SOURCE_DIR}/modules/*/include/" )
    message("INCLUDE_GLOB = ${opencv_include_modules}")
    include_directories( ${opencv_include_modules} )

