/// <reference types="emscripten" />

declare module "read-dicekey-js" {

    export class DiceKeyImageProcessor {
        constructor();
        //   .function("processJsImageData", &DiceKeyImageProcessor::processJsImageData)
        processJsImageData: (width: number, height: number, data: Uint8ClampedArray | Buffer) => Boolean;
        //    .function("renderAugmentationOverlay", &DiceKeyImageProcessor::renderAugmentationOverlay)
        renderAugmentationOverlay: (width: number, height: number, data: Uint8Array) => Boolean;
        // .function("diceKeyReadJson", &DiceKeyImageProcessor::jsonKeySqrRead)
        diceKeyReadJson: () => String;
        // .function("isFinished", &DiceKeyImageProcessor::isFinished)  }
        isFinished: () => Boolean;
        // All embind-generated objects are given a delete() method to destruct and clean up memory
        delete: () => void;
    }

    export interface DiceKeyImageProcessorModule extends EmscriptenModule {
        DiceKeyImageProcessor: new () => DiceKeyImageProcessor;
    }

    // IF ES6, then use
    interface DiceKeyImageProcessorModulePromise {
        then: (fn: (DiceKeyImageProcessor: DiceKeyImageProcessorModule) => any) => void
    }

    // Mirroring the last line of the .js file generated by emscripten in es6 mode
    const Module: () => DiceKeyImageProcessorModulePromise;
    export default Module;

}